### ISSUE TITLE
Using Basic-Video Chat inside docker.

### ISSUE THREAD

**Issue by rutvikjoshi7** [opentok/opentok-linux-sdk-samples#28]
In my use case, I just want to use the subscriber part of the basic-video chat inside docker. I am getting this error:- [ERROR] otk_peer_connection.cpp:1999 - Error creating webrtc default AudioDeviceModule. I have seen your soution at [https://github.com/opentok/opentok-linux-sdk-samples/issues/16#issuecomment-723145737](url), however, the implementation was not successful. I will appreciate a proper solution to this problem.
![Screenshot from 2021-12-25 23-29-06](https://user-images.githubusercontent.com/96751603/147511619-31c136c9-bd9e-42b2-bc23-0af6f55d66c5.png)

**Comment by rutvikjoshi7** [comment]
It can also help if you can tell me how to disable audio for basic-video chat. I don't need Audio for my used case.

**Comment by v-kpheng** [comment]
@rutvikjoshi7, to disable audio, you can do the following:

```
otc_publisher_settings* publisher_settings = otc_publisher_settings_new();
otc_publisher_settings_set_audio_track(publisher_settings, OTC_FALSE);
```

More details here: https://tokbox.com/developer/sdks/linux/reference/publisher_8h.html#af2994146c00d89083d00db21b16bc892

<img width="1286" alt="image" src="https://user-images.githubusercontent.com/49660118/192673645-b15c5c98-8ca1-4265-b685-247fdfe4f411.png">

Closing, since that should be sufficient.
